# Generated by Django 5.2 on 2025-04-27 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_address_created_by'),
        ('drivers', '0002_remove_driver_status_driver_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_arrival_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_services', to='drivers.driver')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_services', to='addresses.address')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'indexes': [models.Index(fields=['status'], name='services_se_status_288ecc_idx')],
            },
        ),
    ]
