# Generated by Django 5.2 on 2025-04-27 22:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_created_by'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_services', to='addresses.address'),
        ),
    ]
