# Generated by Django 5.2 on 2025-04-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cancellation_reason',
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=15),
        ),
    ]
