# Generated by Django 5.2 on 2025-04-28 14:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code. This value may contain only letters, numbers, spaces and hyphens.', regex='^[0-9a-zA-Z\\s-]+$')]),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'state', 'country'], name='addresses_a_city_f4a49b_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['latitude', 'longitude'], name='addresses_a_latitud_d6cc10_idx'),
        ),
    ]
