# Generated by Django 5.2 on 2025-04-29 05:32

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='addresses_a_latitud_d6cc10_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.AddField(
            model_name='address',
            name='coordenates',
            field=django.contrib.gis.db.models.fields.PointField(default=Point((0,0)), geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
