# Generated by Django 5.2 on 2025-04-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_remove_address_addresses_a_latitud_d6cc10_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='coordenates',
            new_name='coordinates',
        ),
    ]
