# Generated by Django 5.2 on 2025-04-29 06:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_rename_coordenates_address_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, geography=True, srid=4326),
        ),
    ]
