# Generated by Django 5.2 on 2025-04-27 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_color', models.CharField(max_length=30)),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BUSY', 'Ocupado'), ('OFFLINE', 'Fuera de servicio')], default='OFFLINE', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=('users.user', models.Model),
        ),
    ]
