# Generated by Django 5.2 on 2025-04-29 06:07

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_status_driver_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='driver',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, default=Point((0,0)), geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
